version: '3.8'
services:
  backend:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres
      - mongo
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '4000:80'
    env_file:
      - .env
    depends_on:
      - postgres
    logging:
      driver: none

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_db:/data/db
    env_file:
      - .env
    logging:
      driver: none

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo
volumes:
  postgres_db:
  mongo_db:
