version: '3.8'
services:
  backend:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres
      - neo
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '4000:80'
    env_file:
      - .env
    depends_on:
      - postgres
    logging:
      driver: none

          ## Defining the Neo4j Database Service        
  neo:
      # The image to use
      image: neo4j:4.4.14
      # map the ports so we can check the db server is up
      ports: 
          - 7474:7474
          - 7687:7687
      # mounting a named volume to the container to track db data
      volumes:
          - neo4j_data:/data/
      env_file:
          - .env
volumes:
  db:
  neo4j_data:
