version: '3.8'
services:
  backend:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '4000:80'
    env_file:
      - .env
    depends_on:
      - postgres
    logging:
      driver: none
volumes:
  db:
