version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    steps:
      - checkout
      - setup_remote_docker:
        version: 20.10.14

version: 2.1

orbs:
  node: circleci/node@3.0.0
  
  jobs:
    build:
      docker:
        - postgres:
            - image: postgres:13
            
            enviroment:
              
          
services:
  postgres:
    image: postgres:13
    ports: ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db
    options:
      - health-cmd: pg_isready
      - health-interval: 10s
      - health-timeout: 5s
      - health-retries: 5
