version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    steps:
      - checkout
      - run: docker build . -t kvalifik/kvalifik-image --target=test
      - run: cp .env.ci .env
      - run: docker run --env-file=.env --net=host kvalifik/kvalifik-image npm run lint
      - run: docker run --env-file=.env --net=host kvalifik/kvalifik-image npm run build
      - run: |
          docker run --env-file=.env --net=host kvalifik/kvalifik-image npx typeorm migration:run
          docker run --env-file=.env --net=host kvalifik/kvalifik-image npx typeorm schema:log | grep "Your schema is up to date"
      - run: docker run --env-file=.env --net=host kvalifik/kvalifik-image npm run test
      - run: docker run --env-file=.env --net=host kvalifik/kvalifik-image npm run test:e2e

services:
  postgres:
    image: postgres:13
    ports: ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db
    options:
      - health-cmd: pg_isready
      - health-interval: 10s
      - health-timeout: 5s
      - health-retries: 5
